name: 🧩 Task
description: General task or internal work item
title: "[Task]: "
labels: ["task"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Use this template for internal tasks or actionable work items.

  - type: input
    id: goal
    attributes:
      label: Task Goal
      description: What needs to be done?
      placeholder: "Set up CI pipeline"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Task Description
      description: Detailed description of the task
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: When should this task be considered complete?
      placeholder: |
        - CI runs on every PR
        - Build fails on lint errors

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - High
        - Medium
        - Low
    validations:
      required: true
